CREATE TABLE payments (
  id UUID PRIMARY KEY,
  merchant_id VARCHAR(128) NOT NULL,
  status VARCHAR(16) NOT NULL,
  card_number_last_four VARCHAR(4) NOT NULL,
  expiry_month INTEGER NOT NULL,
  expiry_year INTEGER NOT NULL,
  currency VARCHAR(3) NOT NULL,
  amount INTEGER NOT NULL,
  idempotency_key VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  authorization_in_progress BOOLEAN NOT NULL,
  reversal_attempts INTEGER NOT NULL DEFAULT 0,
  next_reversal_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT payments_merchant_idempotency_unique UNIQUE (merchant_id, idempotency_key)
);

CREATE INDEX payments_reversal_due_idx ON payments (status, next_reversal_at);

CREATE TABLE reconciliation_reports (
  id UUID PRIMARY KEY,
  report_date DATE NOT NULL UNIQUE,
  source_file VARCHAR(255) NOT NULL UNIQUE,
  imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
  row_count INTEGER NOT NULL,
  issue_count INTEGER NOT NULL
);

CREATE TABLE reconciliation_issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id UUID NOT NULL REFERENCES reconciliation_reports(id),
  issue_type VARCHAR(64) NOT NULL,
  reference VARCHAR(64),
  details VARCHAR(512) NOT NULL
);